
CREATE OR REPLACE TASK CKAN_SPOKE_URL_REFRESH
warehouse ='OPEN_DATA_VWH'
USING CRON 0 13 * * *
AS
BEGIN
  CALL SP_UPDATE_RESOURCES();  
END;

alter task ckan_url_refresh resume;

execute task CKAN_URL_REFRESH;